### ISSUE TITLE
polyline，自动计算多线段锚点，能否让折点居中，始终靠右看着不太舒服

### ISSUE THREAD

**Issue by shuangovo** [le5le-com/topology.js#10]
![image](https://user-images.githubusercontent.com/54254822/150901636-11ccac2f-f266-4213-9670-2ff16c8a8ac6.png)
默认是上面的，我想要下面这样的

**Comment by SignDawn** [comment]
已经解决了，拉最新的代码即可。
npm 包尚未发布！

**Comment by shuangovo** [comment]
行
