### ISSUE TITLE
连接线的方法connectLine方法有Bug

### ISSUE THREAD

**Issue by yang0124** [le5le-com/topology.js#100]
官网上的案例方法写的参数
![image](https://user-images.githubusercontent.com/57937078/184781069-be2ab8fb-dc80-4650-87d6-0bd4c2dd7afd.png)
对应源码的参数对应不上
![image](https://user-images.githubusercontent.com/57937078/184781158-e9c42c14-646a-4584-b7a3-0911e5ede8b8.png)

![image](https://user-images.githubusercontent.com/57937078/184781308-0ee865c2-4373-4ca0-8960-17d95f5e72f7.png)

**Comment by ananzhusen** [comment]
connectLine方法重写了，官网文档将在之后更新
