### ISSUE TITLE
矩形边框左上角有缺口

### ISSUE THREAD

**Issue by zhongguohua1993** [le5le-com/topology.js#102]
当画布放大或画笔边框较宽时，矩形画笔左上角会有个缺口
![image](https://user-images.githubusercontent.com/17637843/184873238-469714c5-e6cf-4c22-b4c6-00c7d1546180.png)

**Comment by ananzhusen** [comment]
![image](https://user-images.githubusercontent.com/48847159/186085536-5d51561c-f172-4fcb-8428-a94be96ad52a.png)

可以通过配置末端样式调节
