### ISSUE TITLE
【不懂就问】es5怎么运行啊？

### ISSUE THREAD

**Issue by luleipo** [le5le-com/topology.js#103]
首先，运行的vue样例，太low了，不知道是不是我的方法不对![image](https://user-images.githubusercontent.com/33919004/185061396-68b4469a-e932-4a78-9968-e9b6f1e76702.png)
其次，想着运行es5，dist/topology/topology.js已经生成成功。但是不知道怎么运行项目，求一个小白入门步骤。

**Comment by ananzhusen** [comment]
vue样例已经包含了很多常用功能，更多请学习官方文档，es5直接打开html文件即可
