### ISSUE TITLE
bug:组合后整个画布缩放，执行撤回后，元素的大小未计算缩放比

### ISSUE THREAD

**Issue by 1261960504** [le5le-com/topology.js#11]
复现步骤：
1、拖拽3个相同元素：
<img width="780" alt="屏幕快照 2022-02-18 下午2 08 56" src="https://user-images.githubusercontent.com/25954437/154628178-f6d9aaff-1e5e-4d10-be83-4b92ad45ab43.png">

2、组合其中两个元素：
<img width="546" alt="屏幕快照 2022-02-18 下午2 10 07" src="https://user-images.githubusercontent.com/25954437/154628150-b5e9eb98-c0ca-4c0f-885f-cd764156b4f3.png">

3、整个画布放大：
<img width="599" alt="屏幕快照 2022-02-18 下午2 10 25" src="https://user-images.githubusercontent.com/25954437/154628025-edd20ec2-9e26-43bf-a41c-002a21bd1a05.png">

4、执行撤回：
<img width="646" alt="屏幕快照 2022-02-18 下午2 10 37" src="https://user-images.githubusercontent.com/25954437/154628329-dad7f329-90d4-4f7c-afc0-2fe97c59ad79.png">

5、效果如下，未计算缩放比，导致大小与原元素大小不同：
<img width="552" alt="屏幕快照 2022-02-18 下午2 10 48" src="https://user-images.githubusercontent.com/25954437/154628460-bfb1d79b-1371-420c-aacd-8913ca0112d2.png">

**Comment by SignDawn** [comment]
已修复，源码直接拉取即可， npm 包尚未发布预计 1.1.3 更新

**Comment by SignDawn** [comment]
已修复，源码直接拉取即可， npm 包尚未发布预计 1.1.3 更新
