### ISSUE TITLE
复制粘贴文字bug    大佬 怎么回事 修复一个bug 产生一个新的bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#110]
![22](https://user-images.githubusercontent.com/20244432/187344973-ebca4246-b2a9-4b60-9ced-ab798f87bbea.gif)

**Comment by Blizzard-liu** [comment]
![33](https://user-images.githubusercontent.com/20244432/187345337-c1aec1fe-0d98-48b0-91eb-3a5ba9d27d4f.gif)

**Comment by ananzhusen** [comment]
最新版本已处理
