### ISSUE TITLE
[建议]支持 HTML5 以及 SVG 元素节点

### ISSUE THREAD

**Issue by jshenguru** [le5le-com/topology.js#114]
能否增加支持 HTML5 以及 SVG 元素节点？

类似 fabric.js 中的功能。在线演示编辑器 https://salgum1114.github.io/react-design-editor/

组态中这两种节点用的还蛮多的。

![Screenshot_2022-09-04_19-35-08](https://user-images.githubusercontent.com/26332171/188337864-c65e470e-9368-4a2f-b845-1f0ca470bf96.png)

**Comment by ananzhusen** [comment]
dom图元已经有相关实例，例如echarts、gif都是以dom方式引入的图元。svg图元可以以图片方式引入，topology支持解析简单的svg图

**Comment by jshenguru** [comment]
如何在 le5le 的在线编辑器中往画布添加诸如  <div>Hello World!</div> 这样的 HTML 元素？

**Comment by jshenguru** [comment]
> dom图元已经有相关实例，例如echarts、gif都是以dom方式引入的图元。svg图元可以以图片方式引入，topology支持解析简单的svg图

谢谢你的回答。我想请教，如何在 le5le 的在线编辑器中往画布添加诸如  “<div>Hello World!</div>” 这样的 HTML 元素？

**Comment by ananzhusen** [comment]
自定义组件（https://developer.le5le.com/tutorial/make-component.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E5%BD%A2%E5%BA%93），再参考gif/dom

**Comment by a445073286** [comment]
> 自定义组件（[https://developer.le5le.com/tutorial/make-component.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E5%BD%A2%E5%BA%93），再参考gif/dom](https://developer.le5le.com/tutorial/make-component.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E5%BD%A2%E5%BA%93%EF%BC%89%EF%BC%8C%E5%86%8D%E5%8F%82%E8%80%83gif/dom)

你好，这个连接失效了，可以再发一个有效的链接吗

**Comment by ananzhusen** [comment]
https://doc.le5le.com/document/119832713  参考echarts
