### ISSUE TITLE
求助,如果网络拓扑没有具体位置,能自动布局么?

### ISSUE THREAD

**Issue by UvDream** [le5le-com/topology.js#120]
如果网络图谱没有具体节点位置,只有节点之间的关系,这种能自动编排算法吗?

**Comment by ForestHo** [comment]
> 如果网络图谱没有具体节点位置,只有节点之间的关系,这种能自动编排算法吗?

你说的是根据js代码自动成图？这个需要自己写 成图算法，或者找我们定制开发，我们在电网单线图，电网拓扑图，脑图，流程图等都有成熟且已交付客户使用的成图算法。
