### ISSUE TITLE
【问题】是不是自定义锚点事件有问题

### ISSUE THREAD

**Issue by x8zx** [le5le-com/topology.js#122]
export function ccc(pen, ctx){
  const path = !ctx ? new Path2D() : ctx;
  const { x, y, width, height } = pen.calculative.worldRect;
  path.moveTo(x + width / 2, y);
  path.lineTo(x + width, y + height);
  path.lineTo(x, y + height);
  path.lineTo(x + width / 2, y);

  if (path instanceof Path2D) return path;
}

export function cccAnchors(pen) {
  const anchors = [];
  anchors.push({
    id: '0',
    penId: pen.id,
    x: 100,
    y: 100,
  })
  pen.anchors = anchors;
  console.log(pen)
}

this.canvas.register({ ccc });
this.canvas.registerAnchors({ ccc: cccAnchors });

然后再绘图中，设置的唯一锚点无法展示

**Comment by SignDawn** [comment]
x y 是相对值，小于 1 . 可以设置 0.5 0.5 看看

**Comment by SignDawn** [comment]
https://developer.le5le.com/tutorial/make-component.html

**Comment by x8zx** [comment]
收到，谢谢，当时没有仔细看那句百分比的话
