### ISSUE TITLE
【建议】上下左右四个锚点位置可以选择配置为上下左右四个缩放

### ISSUE THREAD

**Issue by wang11111** [le5le-com/topology.js#14]
目前是根据设定的大小，拖拽出组件，生成组件之后一定是需要调整长宽，没有上下左右单独方向的调整，容易出现偏差

**Comment by SignDawn** [comment]
Shift 快捷键
![image](https://user-images.githubusercontent.com/48878568/156735751-2f55ecf2-ee9a-41e2-9539-8e26357e8ffb.png)
