### ISSUE TITLE
因为页面滚动而变更位置后，交互位置变得不正常

### ISSUE THREAD

**Issue by Soundmark** [le5le-com/topology.js#16]
正常创建一个实例，添加一个图形，滚动后无法在图形位置上选中图形，更新canvas.bounding之后图形选中恢复正常，但是放大缩小的位置又变得不正常。
复现demo：https://codesandbox.io/s/ecstatic-firefly-dd021l?file=/src/App.js

**Comment by SignDawn** [comment]
鼠标错位，执行 resize 方法即可。
放大缩小位置是正常的呀，以鼠标为中心点进行缩放

**Comment by Soundmark** [comment]
https://github.com/le5le-com/topology.js/issues/16#issuecomment-1058979564
resize方法解决这个问题的作用就是更新canvas.bounding，但是如果在滚动的时候用resize会闪烁，滚动发生之后放大缩小不会按照鼠标中心点进行呀，我这个demo可以复现

**Comment by SignDawn** [comment]
#17
