### ISSUE TITLE
控制点如何修改？

### ISSUE THREAD

**Issue by g17ui** [le5le-com/topology.js#165]
<img width="242" alt="image" src="https://user-images.githubusercontent.com/48198890/232659157-2f1f27c1-6dd9-4f5b-8e7b-2afccf4f0462.png">
官网中选中连线时的样式配置中的控制点是由什么API控制的，没在文档中找到相关说明。

**Comment by SignDawn** [comment]
pen.calculative.worldAnchors  每个点的 prev 和 next 就是控制点，更改它就成。
可能还需要反 计算 pen.anchors ，试试 initLineRect
