### ISSUE TITLE
【建议】是否考虑组件的翻转功能

### ISSUE THREAD

**Issue by wang11111** [le5le-com/topology.js#18]
水平翻转，垂直翻转

**Comment by SignDawn** [comment]
文档 flip ，
![image](https://user-images.githubusercontent.com/48878568/157636908-898fccb5-c480-40c9-b0a8-c7f1c114b2ed.png)

**Comment by wang11111** [comment]
测试了一下，目前是否组合图形不能翻转

**Comment by SignDawn** [comment]
已修复，下个版本更新。http://developer.le5le.com/topology-documents/tutorial/changelog.html#bug-fixes

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/160334417-6b418344-6a89-4189-bd03-87247c908377.png)
