### ISSUE TITLE
topology.active(pens);

### ISSUE THREAD

**Issue by bicitechfed** [le5le-com/topology.js#2]
调用这个api会报错：如下
react-dom.development.js:4091 Uncaught TypeError: Cannot set properties of undefined (setting 'active')
    at eval (canvas.ts:2505)
    at Array.forEach (<anonymous>)
    at Canvas.active (canvas.ts:2504)
    at Topology.active (core.ts:861)
    at handleSelectedNode (CanvasNodes.tsx:36)
    at onClick (CanvasNodes.tsx:49)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070)

源码：
this.store.active = [];
      pens.forEach(function (pen) {
        pen.calculative.active = true;
        (0,_pen__WEBPACK_IMPORTED_MODULE_22__.setChildrenActive)(pen);
      });

**Comment by SignDawn** [comment]
传入的 pens 是来自于 topology.store.data.pens 中的吗？
如果不是，你需要确保存在 pen.calculative 是否存在。

**Comment by hsbtr** [comment]
> 传入的 pens 是来自于 topology.store.data.pens 中的吗？ 如果不是，你需要确保存在 pen.calculative 是否存在。

此项设计是否有意向修改呢，在使用过程中相信大家比较喜欢用的是topology.data()获取图纸数据，而不是topology.strore.pens毕竟大家看文档使用的结果发现对传入的数据还有要求

**Comment by hsbtr** [comment]
> 传入的 pens 是来自于 topology.store.data.pens 中的吗？ 如果不是，你需要确保存在 pen.calculative 是否存在。

此项设计是否有意向修改呢，在使用过程中相信大家比较喜欢用的是topology.data()获取图纸数据，而不是topology.strore.pens毕竟大家看文档使用的结果发现对传入的数据还有要求，同时这个api在执行以后需要手动执行一遍render()或者鼠标进入画布区才会生效

**Comment by SignDawn** [comment]
topology.data() 存储的时候再去调用，其他时候都使用 topology.store.data.pens 。

**Comment by hsbtr** [comment]
> topology.data() 存储的时候再去调用，其他时候都使用 topology.store.data.pens 。

好吧；这样的话建议在文档中标注一下；很多人不了解的情况下都是直接使用topolog.data()

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/190150148-aaef4a4b-7e8b-4310-8424-9cca1aeff26f.png)
文档一直都有写，很多人不看文档罢了

**Comment by hsbtr** [comment]
> ![图片](https://user-images.githubusercontent.com/48878568/190150148-aaef4a4b-7e8b-4310-8424-9cca1aeff26f.png) 一直在写文档，很多人不看装

还真没注意到这里，一般都是先看是教程那里的api简介

**Comment by hsbtr** [comment]
> ![图片](https://user-images.githubusercontent.com/48878568/190150148-aaef4a4b-7e8b-4310-8424-9cca1aeff26f.png) 一直在写文档，很多人不看装

之前都是先看教程那里的api简介；这回学会了还是要两处多看看
