### ISSUE TITLE
【疑问】设置option的background后，通过setBackgroundImage设置背景图片不生效

### ISSUE THREAD

**Issue by wang11111** [le5le-com/topology.js#21]
个人感觉，背景图片的优先级应该高于背景图片
demo测试如下
`onMounted(() => {
  var topology =  new Topology("topology",{background:'red'});
  topology.setBackgroundImage("http://localhost:3000/src/assets/images/favicon.ico")
});`

**Comment by SignDawn** [comment]
你可以关注一下源码就会发现，backgroundImage 与 backgrondColor 不在同一层，不在同一个 dom 元素上，背景颜色是用 canvas 绘制的，而背景图片只是 dom 的一个 css 属性。
canvas 相对于 dom 是在上层的，所以背景颜色优先级更高，不予解决，你可以设置背景图片后把背景颜色清除掉。

**Comment by hsbtr** [comment]
> 你可以关注一下源码就会发现，backgroundImage 与 backgrondColor 不在同一层，不在同一个 dom 元素上，背景颜色是用 canvas 绘制的，而背景图片只是 dom 的一个 css 属性。 canvas 相对于 dom 是在上层的，所以背景颜色优先级更高，不予解决，你可以设置背景图片后把背景颜色清除掉。

背景图颜色清除使用meta2d.store.data.background = null，没有生效是我使用错了吗
