### ISSUE TITLE
关于旋转后组合再操作图形就会异常的问题

### ISSUE THREAD

**Issue by tckxjzc** [le5le-com/topology.js#22]
if (pen.width > 1 && !isEqual(pen.height, 1)) {
      rect.width = pen.width;
    }
    if (pen.height > 1 && !isEqual(pen.height, 1)) {
      rect.height = pen.height;
    }
没明白calcWorldRects方法中这段的作用，这个会导致宽大于高的图形旋转90度后参与组合必定出问题；

**Comment by SignDawn** [comment]
js 计算误差，这里的含义是 大于1但接近1 认为是1 ，比如说 1.000000000004 认为是 1，代码写错了，拉最新的，上面是 pen.width

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/159826198-571682fd-9cb1-47b9-bece-be0914e42dd2.png)

**Comment by tckxjzc** [comment]
> js 计算误差，这里的含义是 大于1但接近1 认为是1 ，比如说 1.000000000004 认为是 1，代码写错了，拉最新的，上面是 pen.width

更新了，但还是异常，一个宽大于高的图形旋转90度再和一个小于它的宽的图形组合，组合后它的width大于1，再操作，它的width直接变成这个大于1的超小的数了，整个图形变形了

**Comment by tckxjzc** [comment]
组合前
![Screen Shot 2022-03-24 at 10 08 52 AM](https://user-images.githubusercontent.com/19629195/159828088-4d56a192-8761-4f57-b972-ff11d1fc86dd.png)


![Screen Shot 2022-03-24 at 10 09 11 AM](https://user-images.githubusercontent.com/19629195/159828049-ed6936c2-a322-4e50-8d38-b69883e2deba.png)
组合后 再移动下

**Comment by tckxjzc** [comment]
> ![image](https://user-images.githubusercontent.com/48878568/159826198-571682fd-9cb1-47b9-bece-be0914e42dd2.png)

注释掉这段代码就正常了

**Comment by SignDawn** [comment]
后续会看一下的，注释掉这段代码会引发其它问题的，注释不是解决问题的办法，重要的是理解，如果你认为注释是解决问题的办法话，建议你注释全部代码

**Comment by SignDawn** [comment]
暂且注释了，不确定是否会引发其它的 bug，你可以拉最新的了，刚提交！

**Comment by SignDawn** [comment]
@tckxjzc  关于此次修改的解释。   https://le5le.gitee.io/topology-documents/tutorial/version-record.html
