### ISSUE TITLE
钢笔绘制的闭合图形，禁用锚点再操作就显示不出来

### ISSUE THREAD

**Issue by tckxjzc** [le5le-com/topology.js#23]
![Screen Shot 2022-03-30 at 4 37 13 PM](https://user-images.githubusercontent.com/19629195/160789072-096ac194-bec7-49ff-a04b-effbd97791a8.png)
禁用后，再移动下就变成这样
![Screen Shot 2022-03-30 at 4 40 03 PM](https://user-images.githubusercontent.com/19629195/160789419-75bce140-d6ec-47f5-9582-d57ac63ead2f.png)
了

**Comment by SignDawn** [comment]
已修复，预计 1.1.3 版本更新，官网待发布，thanks
