### ISSUE TITLE
【建议】使用钢笔节点在绘制的时候，如果鼠标移入另一个节点范围内，再单击，会默认与这个节点的锚点自动连接

### ISSUE THREAD

**Issue by wang11111** [le5le-com/topology.js#29]
自动连接锚点确实很方便，但是在一些场景，比如圆的内部绘制就无法进行；建议从可以是钢笔节点从外部进入内部一定范围，就不自动连接到锚点

**Comment by wang11111** [comment]
![7bb839db87c9da9643b2b83be56f2e7](https://user-images.githubusercontent.com/14358013/161920102-f2a8f59a-9d39-4fac-94f4-b2c0f3d7a006.png)

![602a22edb8d4f08f6e38de587f0727d](https://user-images.githubusercontent.com/14358013/161920121-94a07b4b-c611-40da-9eb0-0114999b4665.png)

**Comment by SignDawn** [comment]
如何判断一定范围呢？给出怎样的一个计算公式？没有必要。
部分场景，关掉自动锚点即可
