### ISSUE TITLE
画布设置背景图片bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#30]
![image](https://user-images.githubusercontent.com/20244432/162107277-5b88d0f1-f788-4eb2-88fb-6c0db4b0462f.png)
![image](https://user-images.githubusercontent.com/20244432/162107406-6bfd5382-2745-42d5-a645-5a147011ad9a.png)

**Comment by SignDawn** [comment]
bs 架构，不建议试用文件协议，没啥意义，自己做个上传文件的模块。
如果硬要做的话，看下源码，自己提个 pr，画布背景图片使用的是 dom 的 backgroundImage
