### ISSUE TITLE
两个节点进行组合，然后通过topology.addPens(pens)方法插入组合后的新节点报错了

### ISSUE THREAD

**Issue by jojoni9393** [le5le-com/topology.js#31]
两个节点进行组合，然后通过topology.addPens(pens)方法插入组合后的新节点报错了

**Comment by SignDawn** [comment]
pens 传的是什么？若传入的是 三个 pens ，那么一定要确保父节点是在数组的前面

**Comment by SignDawn** [comment]
若仍不行，请参照源码 dropPens
