### ISSUE TITLE
两个节点进行组合，然后选中其中一个节点，通过topology.changePenId方法修改选中节点的id，报错了

### ISSUE THREAD

**Issue by jojoni9393** [le5le-com/topology.js#32]
两个节点进行组合，然后选中其中一个节点，通过topology.changePenId方法修改选中节点的id，报错了

**Comment by jojoni9393** [comment]
两个节点进行组合，然后选中combine节点，通过topology.changePenId方法修改combine节点的id，报错了

**Comment by SignDawn** [comment]
已修复，预计 1.1.4 发布，可拉最新的代码测试
