### ISSUE TITLE
空白图纸,先点开缩略图,在缩略图点击一下,再添加图形,直接报错.

### ISSUE THREAD

**Issue by rolitter** [le5le-com/topology.js#33]
## 版本
v1.1.1

## 复现地址
http://t.le5le.com/

## 复现步骤

空白图纸,先点开缩略图,在缩略图点击一下,再添加图形,直接报错

![le5le](https://user-images.githubusercontent.com/27326998/163302184-05d23855-a1e4-4b66-9e6d-a66e5a2f6c51.gif)

**Comment by SignDawn** [comment]
已修复，未发布 npm 包，预计在 1.1.5 更新
