### ISSUE TITLE
vue版问题

### ISSUE THREAD

**Issue by pengyong25** [le5le-com/topology.js#34]
试了下Vue版本的事件触发，不支持通过js脚本修改节点的背景颜色，这个后续版本会不会更新，还是只能购买企业版

**Comment by SignDawn** [comment]
怎么写的？是可以的 ，topology.setValue({id: 'xxx', background: '#ff4400ff'})

**Comment by pengyong25** [comment]
用的[topology-vue-ts](https://github.com/le5le-com/topology-vue-ts)这个库里面的代码，topology.setValue({id: 'xxx', text: 'xxx'})有用，topology.setValue({id: 'xxx', background: '#ff4400ff'})没效果

**Comment by SignDawn** [comment]
topology-vue-ts 是老版本的，文档：https://www.yuque.com/alsmile/topology/zolsfu
topology.setValue('fdebbee', {fillStyle: '#ff4400'})
推荐使用新版本 topology.js ，在 examples 下有示例。

**Comment by pengyong25** [comment]
再请教一个问题哈，老版本里面怎么改变节点的坐标啊

**Comment by SignDawn** [comment]
setValue， updateProps ，看文档，文档有写
