### ISSUE TITLE
【bug】beforeRemovePen与beforeRemoveAnchor没有被调用

### ISSUE THREAD

**Issue by hsbtr** [le5le-com/topology.js#35]
版本： 1.1.4
在以下两处没有使用调用定义好的生命周期；导致生命周期声明了也无法正确触发；

![1fc37bbeafc26b8004687267d700956](https://user-images.githubusercontent.com/46487804/163383244-d93eaf2b-0430-4957-9aa6-b4f2cf1b0df0.png)
![1fc37bbeafc26b8004687267d700956](https://user-images.githubusercontent.com/46487804/163383278-ab887782-3b47-4aad-9407-8ae90a1af96b.png)

**Comment by SignDawn** [comment]
源码已经完善，预计 1.1.5
