### ISSUE TITLE
修改表格数据 保存后 页面不生效

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#36]
![image](https://user-images.githubusercontent.com/20244432/163502009-7af9d084-72b3-4007-8c05-918692ebf745.png)

**Comment by ananzhusen** [comment]
已修复，但操作列任然是不可修改的

**Comment by ananzhusen** [comment]
请期待1.1.14版本

**Comment by Blizzard-liu** [comment]
头像能不能换个 好吓人
