### ISSUE TITLE
1.1.4 导入之前的设计，官网能打开 vue-demo也能打开

### ISSUE THREAD

**Issue by apgk** [le5le-com/topology.js#41]
目前 引入 core 1.1.4版本
1. 官网能打开之前的配置好的json 
2. vue-demo那个也能打开(core 0.2.30)
3. 自己搭建的基于 core1.1.4 就打不开了
发现line.js报错 （worldAnchors 是 空的 undefined ）
export function line(pen, path) {
    if (!path) {
        path = new Path2D();
    }
    if (pen.calculative.worldAnchors.length > 1) {

**Comment by SignDawn** [comment]
之前的设计是哪个版本的？
老版本数据不支持直接在新版本中打开，官网有特殊处理。
若有需要，可在官网打开后再下载 json 。

**Comment by apgk** [comment]
> 
可以了，怎么打印 版本号

**Comment by SignDawn** [comment]
老版本数据没有版本号
新版本数据，json 中有 version 字段

**Comment by apgk** [comment]
> 
topology 不能打印程序版本号？

**Comment by SignDawn** [comment]
topology.VERSION  老版本，但数据不一定是的。
topology.data().version ，新版本

**Comment by apgk** [comment]
> 
明白了，目前试了下，VERSION  没有，目前使用新版都能打印出data().version
