### ISSUE TITLE
描绘图片bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#43]
![lll](https://user-images.githubusercontent.com/20244432/163956533-0ff31e93-d4cc-40e8-8fad-ef702f51090c.gif)
设置描绘图片后  鼠标悬浮或选择图元 应该还是显示描绘图片

**Comment by SignDawn** [comment]
设计如此， hover 优先，其次 active 选中。
如果按照你这个逻辑，那么鼠标是否移上去，是否选中就看不出区别了，不予解决！
