### ISSUE TITLE
缩放画布,手动设置图形的x/y为0,会导致组件越来越小

### ISSUE THREAD

**Issue by rolitter** [le5le-com/topology.js#47]
## 版本
v1.1.5

## 复现地址
http://t.le5le.com/

## 复现步骤

添加图形,缩放画布,手动设置图形的x/y 为0
![缩放设置xy2](https://user-images.githubusercontent.com/27326998/164966798-f931e232-b92a-4d41-bdc3-e7d542018c06.gif)

**Comment by SignDawn** [comment]
是个 bug ，预计下个版本更新，1.1.7
