### ISSUE TITLE
toPng ，画布背景图片参与绘制

### ISSUE THREAD

**Issue by SignDawn** [le5le-com/topology.js#49]
1. 背景图片是采用截取还是缩小或放大？

**Comment by Blizzard-liu** [comment]
大佬 这个库不是你写的吗  咋还自己提bug

**Comment by SignDawn** [comment]
有背景图片的情况：
1. 当画布全部画笔在背景图片范围内时，扩大区域为整个可视区域。
2. 当存在画笔在背景图片范围外时，合并全部画笔区域与背景图片区域。

若无背景图片，与原来相同。

**Comment by SignDawn** [comment]
源码已更新， 1.1.7 版本发布
