### ISSUE TITLE
请问跟 tmagic-editor 比较 有哪些优缺点

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#57]
请问跟  [tmagic-editor](https://github.com/Tencent/tmagic-editor)  比较  有哪些优缺点

**Comment by SignDawn** [comment]
topology 基于 canvas ，性能好，但样式无法像 css 那样自由，用来做组态的。
这玩意基于 dom ，dom 频繁操作会卡顿的，它们是做低代码平台的，场景不同
