### ISSUE TITLE
透明度动画闪烁

### ISSUE THREAD

**Issue by jojoni9393** [le5le-com/topology.js#58]
{"x":0,"y":0,"scale":1,"pens":[{"anchors":[{"id":"0","penId":"dbb6097","x":0.5,"y":0},{"id":"1","penId":"dbb6097","x":1,"y":0.5},{"id":"2","penId":"dbb6097","x":0.5,"y":1},{"id":"3","penId":"dbb6097","x":0,"y":0.5}],"animateCycle":null,"animateType":"custom","children":[],"fontSize":12,"form":[{"isNotString":true,"key":"data","language":"json","name":"数据","title":"数据","type":"code"},{"key":"x","name":"x","type":"number"}],"frames":[{"bkType":0,"duration":3000,"globalAlpha":0.5,"strokeType":0,"visible":true},{"bkType":0,"duration":3000,"globalAlpha":1,"strokeType":0,"visible":true}],"height":100,"id":"dbb6097","lineHeight":1.5,"lineWidth":1,"name":"square","rotate":0,"showDuration":6000,"text":"正方形","width":100,"x":758,"y":243}],"origin":{"x":0,"y":0},"center":{"x":0,"y":0},"paths":{},"src":"000000000000000000000000","name":"topology.2022/5/6 09:50:05","desc":"","locked":0,"mqttOptions":null,"image":"/image/topology/thumb_491f5125e2f6e8fc.png","class":"","component":false,"folder":"","userId":"6243b685cd9a3a35b7e9ac29","username":"黄腾🏃","editorId":"6243b685cd9a3a35b7e9ac29","editorName":"黄腾🏃","shared":false,"star":0,"view":1,"recommend":-1,"tags":null,"createdAt":"2022-05-06T01:50:07.778Z","updatedAt":"2022-05-06T01:50:07.778Z","version":"1.1.5"}

**Comment by jojoni9393** [comment]
想实现的效果是透明度从1变成0.5变成1变成0.5一直无线循环，但是会闪烁

**Comment by jojoni9393** [comment]
{"x":0,"y":0,"scale":1,"pens":[{"text":"正方形","width":100,"height":100,"name":"square","form":[{"key":"data","type":"code","name":"数据","title":"数据","language":"json","isNotString":true},{"key":"x","type":"number","name":"x"}],"id":"44211dbd","children":[],"x":559,"y":197,"lineWidth":1,"fontSize":12,"lineHeight":1.5,"anchors":[{"id":"0","penId":"44211dbd","x":0.5,"y":0},{"id":"1","penId":"44211dbd","x":1,"y":0.5},{"id":"2","penId":"44211dbd","x":0.5,"y":1},{"id":"3","penId":"44211dbd","x":0,"y":0.5}],"rotate":0,"animateType":"custom","frames":[{"duration":3000,"visible":true,"strokeType":0,"bkType":0,"progress":0.8},{"duration":3000,"visible":true,"strokeType":0,"bkType":0,"progress":0.5}],"showDuration":6000,"visible":true,"progress":0.19,"animateCycle":null,"keepAnimateState":false}],"origin":{"x":0,"y":0},"center":{"x":0,"y":0},"paths":{},"src":"000000000000000000000000","name":"topology.2022/5/6 09:50:05","desc":"","locked":0,"mqttOptions":null,"image":"/image/topology/thumb_aee0fabd03b76077.png","class":"","component":false,"folder":"","userId":"6243b685cd9a3a35b7e9ac29","username":"黄腾🏃","editorId":"6243b685cd9a3a35b7e9ac29","editorName":"黄腾🏃","shared":false,"star":0,"view":1,"recommend":-1,"tags":null,"createdAt":"2022-05-06T01:50:07.778Z","updatedAt":"2022-05-06T01:50:07.778Z","version":"1.1.5"}

**Comment by jojoni9393** [comment]
进度动画也是这个问题，想要的效果是0到0.8然后0.8到0.5，实际效果是0到0.8然后0到0.5，上一个动画没有被保存下来

**Comment by Alsmile** [comment]
fixed
