### ISSUE TITLE
事件 执行自定义脚本 bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#64]
![image](https://user-images.githubusercontent.com/20244432/168542403-b96459c6-0105-4916-9fd1-6c64c543f0c7.png)
![image](https://user-images.githubusercontent.com/20244432/168542528-d02e951a-09c8-4f4f-88ea-11279fd8150c.png)
![image](https://user-images.githubusercontent.com/20244432/168542727-ac916941-3a27-46ab-aa82-8b9d2dc31bb4.png)

**Comment by SignDawn** [comment]
setVisible
