### ISSUE TITLE
事件点击执行脚本 bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#66]
事件点击执行脚本 alert  弹框显示的时候  click事件没有回调  点击确定后才回调  虽然鼠标点击在空白处  但此时焦点依然在组件上 点击空白还是会继续执行    官网没有复现这个问题
https://user-images.githubusercontent.com/20244432/169436057-b8f41ed5-ae91-4ef8-9251-34c80bc63ffc.mp4

**Comment by SignDawn** [comment]
topology 新增了一个方法 clearHover ，你在关闭对话框的同时，调用一下这个方法，预计 1.1.15 版本发布！
如果问题解决了，把问题关掉！

**Comment by Blizzard-liu** [comment]
好的 大佬

**Comment by Blizzard-liu** [comment]
牛啊 大佬  问题解决了
