### ISSUE TITLE
建议源码中增加 dist 文件夹

### ISSUE THREAD

**Issue by ArgoZhang** [le5le-com/topology.js#67]
建议源码中增加 dist 文件夹，方便其他人员直接使用输出 topology.js 文件，而无需自己编译

或者从哪里可以获得到这个已经编辑好的 `topology.js` 文件

**Comment by SignDawn** [comment]
自行编译才能拿到最新的，否则每次改动都编译吗？那样每次提交就太多了。
npm topology.js 也可

**Comment by ArgoZhang** [comment]
或者有 cdn 引用吗？总之能下载 `Topology.js` 的地址就可以啦

**Comment by SignDawn** [comment]
没有 cdn ，需要就自己传，npm 上能下载
https://www.npmjs.com/package/topology.js

**Comment by ArgoZhang** [comment]
感谢，就是要的这个地址，你们修复 bug 或者发布新版本后，这个地址的脚本会更新对吧？另外建议一下，这个代码内最好有一个版本号一类的标示，方便版本确认
