### ISSUE TITLE
【建议】绘制的组件保存功能

### ISSUE THREAD

**Issue by wang11111** [le5le-com/topology.js#68]
绘制出来某个组件保存，方便下次绘图可以拖拽复用

**Comment by SignDawn** [comment]
官网，我的组件就是干这个的，创建组件，移入图形，保存就可以了。
![image](https://user-images.githubusercontent.com/48878568/170667717-45d38528-cfd9-4cce-b122-b51dbfaed21d.png)

**Comment by wang11111** [comment]
请问大佬，是使用 toComponent 实现吗？返回的组合图形保存在哪

**Comment by SignDawn** [comment]
是的，官网保存在后端数据库了！
你想保存在哪就保存在哪
