### ISSUE TITLE
阿里oss上的在线图片显示跨域问题

### ISSUE THREAD

**Issue by andyFang94** [le5le-com/topology.js#7]
![image](https://user-images.githubusercontent.com/54627989/149701454-95b10e6e-d335-469b-8737-850a218f9c71.png)

![Uploading image.png…]()

作为节点拖入画布的时候会显示跨域

**Comment by SignDawn** [comment]
要么让图片允许跨域；
要么就自己配个 nginx 代理。
跨域的解决方式可以自行百度。

**Comment by andyFang94** [comment]
> 要么让图片允许跨域； 要么就自己配个 nginx 代理。 跨域的解决方式可以自行百度。

3Q， 已解决
https://help.aliyun.com/knowledge_detail/39518.html?spm=a2c4g.11186623.0.0.372451f3cdAIdj
   参考了阿里的oss配置
  错误原因： 之前配置局限了 ，现在直接配置了通配符  *
