### ISSUE TITLE
事件  添加触发条件 但是不写 事件就不会执行 应该判断下触发条件没空 就执行事件

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#72]
![image](https://user-images.githubusercontent.com/20244432/172743864-e8b7569c-4913-4675-b71c-6e2b92506aab.png)

**Comment by SignDawn** [comment]
b 站视频，交互事件里面提过

**Comment by Blizzard-liu** [comment]
好吧 可能用户不小心点到了 没填条件

**Comment by SignDawn** [comment]
所以留了取消触发条件
