### ISSUE TITLE
在 new Topology时传入的option内的lineWidth字段无效

### ISSUE THREAD

**Issue by zzw105** [le5le-com/topology.js#75]
我看官网文档里面是可以设置全局lineWidth的，但我看了包括option的ts文件好像已经删除了lineWidth吗？取消了的话我该怎么设置钢笔划出线的默认粗细

**Comment by SignDawn** [comment]
topology.store.data.lineWidth

**Comment by zzw105** [comment]
> topology.store.data.lineWidth

感谢感谢
