### ISSUE TITLE
combine 

### ISSUE THREAD

**Issue by hellobq** [le5le-com/topology.js#77]
如果一个节点 name 是 combine，怎么修改它的一些属性。比如 color、background ？

**Comment by SignDawn** [comment]
修改 combine 节点的属性，不影响子节点的绘制结果以及属性。
需要更改具体子节点的属性，children 属性即子节点的 id

**Comment by hellobq** [comment]
您大概没明白我的意思，我用代码示例下：

```js
  const pen1Opt = {
    name: 'rectangle',
    text: '矩形',
    x: 100,
    y: 100,
    width: 100,
    height: 100,
    background: 'green'
  };
  const pen2Opt = {
    name: 'rectangle',
    text: '矩形',
    x: 200,
    y: 200,
    width: 100,
    height: 100,
    background: 'red'
  };
  const pen1 = await topology.addPen(pen1Opt)
  const pen2 = await topology.addPen(pen2Opt)

  topology.combine([pen1, pen2])

  let pens = topology.store.data.pens
  topology.setValue({
    id: pens[pens.length - 1].id,
    background: 'pink'
 })
```

按照这个配置，combine 节点背景色为什么不是 pink 呢：

![image](https://user-images.githubusercontent.com/29953650/175878079-0fcbac46-a94d-4e14-ae26-c4b32bd91a49.png)

**Comment by SignDawn** [comment]
combine 又不是矩形，没有背景颜色的。
就好比三角形的背景颜色只填充三角形以内的，combine 的背景颜色填充哪里的？当作一个矩形填充吗？这不合理，组合仅仅是使这两个图元一起操作而已

**Comment by SignDawn** [comment]
可外接一个矩形，调用 pushChildren 方法，将另外两个 pen 作为子节点填进去

**Comment by hellobq** [comment]
了解了。谢谢 🙏
