### ISSUE TITLE
gif 设置  imageRatio true 无效

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#80]
imageRatio

![image](https://user-images.githubusercontent.com/20244432/175885363-8435713d-9626-4598-a196-494a2f9de327.png)

**Comment by Blizzard-liu** [comment]
https://user-images.githubusercontent.com/20244432/175888294-119e06f7-dd7f-4f67-8098-b70584f40455.mp4

gif 类型选择 png图片 之后  保存比例 失效

**Comment by SignDawn** [comment]
已修复
