### ISSUE TITLE
绘制自定义图形时，插入 drawImage 图片不显示

### ISSUE THREAD

**Issue by hellobq** [le5le-com/topology.js#81]
我这边使用 registerCanvasDraw 来绘制自定义图形，这个图形中要 drawImage 加入图片，但是现在这种写法并不生效：

```js
// drawImageText.jsx
export function drawImageText(ctx, pen) {
  var img = new Image();
  img.src = 'https://mdn.mozillademos.org/files/5395/backdrop.png'
  img.onload = function(){
    ctx.drawImage(
      img,
      pen.calculative.worldRect.x, 
      pen.calculative.worldRect.y,
      pen.calculative.worldRect.width,
      pen.calculative.worldRect.height
    );
  }
} 

// topology.jsx
topology.registerCanvasDraw({ drawImageText })

// config.json
{ 
  key: 'imageText',
  title: '图片',
  data: {
    name: 'drawImageText',
    width: 100,
    height: 100
  }
}
```

请求解答。谢谢。

**Comment by SignDawn** [comment]
不能是异步的。
默认有 image 功能，不用自己写，配置 image 属性就行。
http://t.le5le.com/

**Comment by hellobq** [comment]
恩，默认是有 image 图形。但我想自定义复杂图形来实现 image + rectangle 的效果

**Comment by SignDawn** [comment]
矩形可以配图片，直接加 image 属性

**Comment by SignDawn** [comment]
如果一定要 drawImage ，提早 new 出来，不要在方法里面 new 和 onload

**Comment by hellobq** [comment]
是。但要实现这种效果，不得使用 registerCanvasDraw 来自定义嘛：

![image](https://user-images.githubusercontent.com/29953650/176345709-b775861d-8357-4371-baf0-f6417aefbab3.png)

**Comment by SignDawn** [comment]
如果不考虑(旋转 + resize)，可以用组合 combine，上一个文字，下一个文字，然后组合就行了

**Comment by hellobq** [comment]
是，combine 方式能实现自由组合。但这种就失去从 DOM 拖拽到 canvas 的效果了（即只能拖拽到指定位置）。比如以下，我想做左边拖到 1，其实只能渲染出 2（2 是固定位置的 combine 组合）

![image](https://user-images.githubusercontent.com/29953650/176347051-2cd0b373-d905-4648-8670-e6adf7b74cf1.png)

**Comment by SignDawn** [comment]
你说清楚点，你 dragStart 写的有问题，你传的什么？
官网，我的组件，不就是直接把组合 combine 拖上来？

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/176347622-242d752a-a897-4835-8a11-75b5f3250207.png)

**Comment by hellobq** [comment]
谢谢。我去官网研究下 ，打扰了 🙏
