### ISSUE TITLE
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is an OffscreenCanvas element with a width or height of 0.

### ISSUE THREAD

**Issue by hellobq** [le5le-com/topology.js#83]
初始化 topology、open json 后，如果浏览器分辨率变化，则有报错：

![image](https://user-images.githubusercontent.com/29953650/176413191-c9318f50-9d44-4ff3-9edd-3116ff2d409e.png)

**Comment by SignDawn** [comment]
宽或者高为 0 了，父 dom 元素宽高为 0 ，就报错了
