### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#89]
如图 正方形被禁用 locked = 10
![image](https://user-images.githubusercontent.com/20244432/177498737-ee1c6e9f-ef3e-4c4b-9227-674b25f95531.png)

使用快捷键 ctrl + A 全选  被禁用的正方形也被选择了  应该不能被选择   
![image](https://user-images.githubusercontent.com/20244432/177499133-52a55547-fa8e-4d5e-884e-4e0e46a6ba5b.png)

**Comment by ananzhusen** [comment]
@topology/core 1.1.35修复
