### ISSUE TITLE
[bug]桌面拖拽gif图片 不能播放

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#91]
![4](https://user-images.githubusercontent.com/20244432/178677465-7f24dd28-1cf2-455b-aac5-465ac1c0d16b.gif)

**Comment by SignDawn** [comment]
可以看看 ondrop 方法，自行提个 pr

**Comment by Blizzard-liu** [comment]
我是这么判断的 不知道是不是很严谨
  
  async fileToPen(file: File): Promise<Pen> {
    let url = '';
    if (this.store.options.uploadFn) {
      url = await this.store.options.uploadFn(file);
    } else if (this.store.options.uploadUrl) {
      url = await uploadFile(
        file,
        this.store.options.uploadUrl,
        this.store.options.uploadParams,
        this.store.options.uploadHeaders
      );
    } else {
      url = await fileToBase64(file);
    }
    return new Promise((resolve, reject) => {
      const img = new Image();
      let ext =  url.substring(url.lastIndexOf('.') + 1)
    // console.log('ext == ',ext)
      let name = ext == 'gif' ? 'gif' : 'image'
      img.onload = () => {
        globalStore.htmlElements[url] = img;
        resolve({
          width: img.width,
          height: img.height,
          name,
          disableInput: true,
          imageRatio: true,
          image: url,
        });
      };
      img.onerror = (e) => {
        reject(e);
      };
      img.src = url;
    });
  }
