### ISSUE TITLE
各个插件安装完毕之后，报mqtt的错误

### ISSUE THREAD

**Issue by wwdDongDong** [le5le-com/topology.js#92]
![image](https://user-images.githubusercontent.com/30905492/179193155-64c97ecb-0cf0-48e8-8c50-db5f24ddf1ab.png)
我目前写了一个例子，里面的package.json如下：
![image](https://user-images.githubusercontent.com/30905492/179193399-14b9ae6d-dc63-4164-8fba-dd536d399196.png)

当我使用npm run dev启动项目就报mqtt的错误，这个mqtt的版本我发现是4.3.7，我试着将安装的mqtt删除，又重新安装了4.2.7的版本 这样就运行起来了，这是一个问题，不可能每次安装项目 我们都需要重新对mqtt降低版本，希望可以修复一下

**Comment by wwdDongDong** [comment]
package.json详细信息
{
  "name": "vuetest",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "wwd",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "test": "npm run unit",
    "lint": "eslint --ext .js,.vue src test/unit",
    "build": "node build/build.js",
    "webpack": "webpack --version"
  },
  "dependencies": {
    "@topology/core": "^0.3.8",
    "@topology/activity-diagram": "^0.3.0",
    "@topology/class-diagram": "^0.3.0",   
    "@topology/flow-diagram": "^0.3.0",
    "@topology/sequence-diagram": "^0.3.0",
    "@topology/chart-diagram": "^0.3.0",
    "@topology/layout": "^0.3.0",
    "axios": "^0.18.0",
    "vue": "^2.5.2",
    "vue-router": "^3.1.5",
    "vuedraggable": "^2.23.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^8.2.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "compression-webpack-plugin": "^1.1.11",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

**Comment by SignDawn** [comment]
新项目吗？推荐使用 1.0 版本了，可参照 topology.js 下 examples 的示例

**Comment by wwdDongDong** [comment]
@SignDawn 好的 我去改成1.0版本吧，但是官网目前都不是1.0版本，其实我现在安装的也是0.5.x 其实也报mqtt的错误，我去改成1.0版本试试先。
![image](https://user-images.githubusercontent.com/30905492/179870823-3663be08-4b05-44a2-b39d-789bd1ef07b8.png)

**Comment by SignDawn** [comment]
官网已经是 1 版本了。
语雀文档是老文档了。
官网（http://topology.le5le.com/） => 快速上手就是新文档
新版编辑器（http://t.le5le.com/）

**Comment by wwdDongDong** [comment]
@SignDawn 安装最新版也是这个问题
![image](https://user-images.githubusercontent.com/30905492/179882889-83ee8084-b666-47d4-aedd-17759760ed7c.png)
{
  "name": "topology",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "wwd",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "lint": "eslint --ext .js,.vue src",
    "build": "node build/build.js"
  },
  "dependencies": {
    "@topology/activity-diagram": "^1.0.0",
    "@topology/chart-diagram": "^1.0.0",
    "@topology/class-diagram": "^1.0.0",
    "@topology/core": "^1.1.28",
    "@topology/flow-diagram": "^1.0.0",
    "@topology/layout": "^0.3.0",
    "@topology/sequence-diagram": "^1.0.0",
    "axios": "^0.27.2",
    "element-ui": "^2.15.9",
    "le5le-store": "^1.0.7",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.2.3",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "node-sass": "^4.14.1",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "sass-loader": "^7.3.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
