### ISSUE TITLE
[问题] 使用websocket通信时会提示连接之前被关闭

### ISSUE THREAD

**Issue by hsbtr** [le5le-com/topology.js#99]
查了一下说有超时断连
![image](https://user-images.githubusercontent.com/46487804/181226942-9f1ed7ed-6cc5-48ba-abbb-a9858257ac3d.png)

**Comment by hsbtr** [comment]
补充，后续发现如果是topology.open时将websocket地址带入进去，就不会出现这个警告同时topology.socketFn会触发，反之直接使用topology.connectWebsocket()主动连接则会出现这个警告并且socketFn也不会触发

**Comment by SignDawn** [comment]
socketFn 你在什么时机赋值的？还是说你配置了 store.data.socketCbJs ？方便的话，贴出两套代码吧。
open 的本质也是调用 connectWebsocket 方法

**Comment by hsbtr** [comment]
> socketFn你在配置什么机制的调用？还是说你在配置 store.data.socketCbJs ？

弄了一个简单的demo复现了这个问题，代码在[这里](https://github.com/hsbtr/reproduce-topology-scenes)， 复现的过程中猜测试首次初始化的时候画布上没有数据所以将websocket链接终止掉了

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/182021471-85a02b4f-a4ee-46e9-83ba-e2df09fed380.png)

**Comment by SignDawn** [comment]
open 里最好带上 websocket
http://developer.le5le.com/tutorial/topology.html#%E6%96%87%E4%BB%B6%E6%95%B0%E6%8D%AE

**Comment by hsbtr** [comment]
> 打开里最好带上websocket http://developer.le5le.com/tutorial/topology.html#%E6%96%87%E4%BB%B6%E6%95%B0%E6%8D%AE

明白了，感谢
